### ISSUE TITLE
Use Ubuntu package instead of PIP

### ISSUE THREAD

**Issue by eero-t** [onedr0p/intel-gpu-exporter#13]
As you're already using Ubuntu, you could as well use Ubuntu Python prometheus client package, instead of using PIP: https://packages.ubuntu.com/jammy/python3-prometheus-client

Also, is there some particular reason for using AWS Ubuntu version instead of official Ubuntu base images: https://hub.docker.com/_/ubuntu
?

**Comment by onedr0p** [comment]
Ubuntu is known for not having the latest packages available so I'm pulling directly from the source (pip) which will always have the latest version.

The image I'm using from ECR is just a mirror of the official dockerhub Ubuntu image, which doesn't have rate limits.

**Comment by eero-t** [comment]
> Ubuntu is known for not having the latest packages available so I'm pulling directly from the source (pip) which will always have the latest version.

You can always pick a newer version of Ubuntu too, 23.04 includes the second latest version of prometheus client:
* https://packages.ubuntu.com/lunar/python3-prometheus-client
* https://github.com/prometheus/client_python/releases

And if you're not using the features from the newer releases, does it matter?  Ubuntu should at least be providing updates for the known security issues.

Note: I do not have any strong opinion on this.  It's just that pypi use in general has some issues: https://lwn.net/Articles/919588/

> The image I'm using from ECR is just a mirror of the official dockerhub Ubuntu image, which doesn't have rate limits.

Oh, I see.

=> Feel free to close this ticket.

----

PS. Have you tried Intel XPU manager: https://github.com/intel/xpumanager ?

It offers quite a few additional metrics (and other features) compared to `intel_gpu_top`.

It will require installing Intel user-space drivers though, as it relies on Sysman API: https://spec.oneapi.io/level-zero/latest/sysman/api.html

Due to that, and few other deps that distros are still lacking, it's better to use Intel's distro driver repos: https://dgpu-docs.intel.com/installation-guides/index.html

(Unless you use container version of XPU Manager from DockerHub, but that's lacking behind XPU manager releases.)

**Comment by onedr0p** [comment]
Aye pip npm docker etc.. all have issues with supply chain attacks but I'm not too worried about it here as this is more of a tool to deploy at home.

Feel free to open an issue on supporting xpumanager instead of intel gpu top, looks interesting and I'll take a look into it when I have time. I'm also open to PRs if you wanted to take a look into it as well.

**Comment by eero-t** [comment]
Latest XPUM release is v1.2.11: https://github.com/intel/xpumanager/releases/

There is old official container for v1.0: https://hub.docker.com/r/intel/xpumanager

According to this, it will be updated soon: https://github.com/intel/xpumanager/issues/17

Its exporter is also written in Python, but the whole thing is a quite a bit heavier that yours, so it's nice that you've done a lightweight alternative that works with things already present in distros.
